### ISSUE TITLE
Block URLs which are not publicly available

### ISSUE THREAD

**Issue by daKmoR** [open-wc/wild#10]
URLS like 
- `primefaces.org`
- `testui.joomla.com`
- `accp.mijn.ing.nl`
- `127.0.0.1`

are not reachable and are probably added by accident 😅

this my be even a security leek as it puts part of this internal dom structure onto the public web 🙈

So potentially when adding a new URL a request could be made to make sure this URL is reachable and only add in this case...

**Comment by thepassle** [comment]
How would you check if the URL is reachable? 🤔

**Comment by daKmoR** [comment]
do a fetch request on the "add URL" action... e.g. don't let the client add the URL directly but a "server/service/api" add it.

**Comment by thepassle** [comment]
Closing this in favor of https://github.com/open-wc/locator/issues/25
