### ISSUE TITLE
Show the total number of domains indexed in the home page

### ISSUE THREAD

**Issue by abdonrd** [open-wc/wild#14]

**Comment by emab** [comment]
Mind if I take a look at this?

**Comment by emab** [comment]
Great! Are there any docs on the API used to get the info? Want to avoid downloading all the data and just grab that handy total if possible.

**Comment by emab** [comment]
Has the API been down the last two days?

**Comment by thepassle** [comment]
Hi! Sorry for the slow reply, Ive had some IRL priorities the last few week.

> Has the API been down the last two days?

It looks like it, I've created an issue on the API repo to investigate why this happened (its in a private repo now, but it'll move to public soon ™️) I've restarted it now so its working again.

As for showing the total number of domains indexed, I'm not entirely sure about what the UX of this should look like. I feel like just showing a number above the list is a little... boring somehow 😅 Do you have any ideas/suggestions?

**Comment by emab** [comment]
> Hi! Sorry for the slow reply, Ive had some IRL priorities the last few week.

No problem, hope everything is ok with you!


> I'm not entirely sure about what the UX of this should look like

Yeah me either, there's a few options and it depends how much you want to emphasise the number. 

My initial feeling was to just have it included in the paragraph describing what it on the page, with a slight emphasis. 

![image](https://user-images.githubusercontent.com/8884999/95585051-92108500-0a36-11eb-9064-043d94f1b5d1.png)

**Comment by thepassle** [comment]
Actually quite like that. I dont think we should even make it bold, but just have it blend into the paragraph 'naturally'.

Maybe we can change the text to "Currently, 86 sites have been indexed."? What do you think?

Happy to take a PR for this if you're still interested 🙂 You can find the total amount of sites found in the api call:

![image](https://user-images.githubusercontent.com/17054057/95585829-161b3a80-0a40-11eb-95d8-0a25f9003d1e.png)

**Comment by emab** [comment]
Yeah I think that looks good!

I've opened a PR [here](https://github.com/open-wc/wild/pull/18).

**Comment by thepassle** [comment]
fixed by @emab in https://github.com/open-wc/wild/pull/18

![image](https://user-images.githubusercontent.com/17054057/95588340-97c09780-0a43-11eb-8416-a355c066dcc5.png)
