### ISSUE TITLE
Find more behaviour has no indication what is new

### ISSUE THREAD

**Issue by daKmoR** [open-wc/wild#7]
When clicking on "find more" suddenly the page changes and way more content is there... 
there is however no indicator on what is new or when the new content starts.

therefore I didn't remember the last element from before I have to reread a lot of entries

**Comment by thepassle** [comment]
Yeah, I'd really like to find a better 'pattern' than a 'load more' button

Any suggestions?

**Comment by daKmoR** [comment]
classic pagination? 🤔

if it's good enough for google it could be good enough for us? 😅

**Comment by thepassle** [comment]
I considered this initially, but firestore is weird in that if you want to get the total count of a collection, that counts as as many reads as are in the collection 🤦‍♂️ E.g.: if you have 2000 items in the collection, getting the total amount of items in a collection will cost you 2000 read operations

**Comment by thepassle** [comment]
fixed in 2371940785c53fdacf434ff51d26136ac867ef49
